modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
credits = ""
displayName="${mod_name}"
logoFile = "icon.png"
authors="${mod_authors}"
description='''${mod_description}'''
mixinConfig = "myth_wizardry.mixins.json"

[[dependencies.myth_wizardry]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.myth_wizardry]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.myth_wizardry]]
modId="ebwizardry"
mandatory=true
versionRange="[0.8.5,0.9)"
ordering="AFTER"
side="BOTH"
